collections:
  texts:
    output: true
    authors:
      output: true
      genetic:
        permalink: /texts/:author/:title/genetic.html
      diplomatic:
        permalink: /texts/:author/:title/diplomatic.html

# rgb values for coloring
light: 253, 216, 53
dark: 40, 40, 40

# site text
tagline: Visualizing Ezra Pound's revisions
name: Genetic Pound

# repo name
baseurl: /variant-viewer